name = "CrossGrove"
author = "Spookipup"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e4f712296c523ddb0955effa61cbddfb99e8ef4b060e73ab6002cdf484c00db"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
