name = "CrossGrove"
author = "Spookipup"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f25a878961a4d4d1f6699f2180f5c3e14d5cff22dee76dd50d1d5a7d511e6f57"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
