name = "CrossGrove"
author = "Spookipup"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9450f60fd5a22f4cf696ad610996f5c232784c5246847d418d1a5610f7cfe51c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
